namespace RazorWings.Compiler.CodeGen;

using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using RazorWings.Compiler.Models;

/// <summary>Generates dependency-free JavaScript for the supported Razor subset.</summary>
public sealed class JavaScriptEmitter
{
    public string GenerateJavaScriptCode(ComponentModel component, ReactionGraph reactionGraph)
    {
        if (!component.IsValid)
            throw new ArgumentException("Component model must be valid before code generation");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated from {Path.GetFileName(component.SourcePath)} component");

        foreach (var child in FindComponents(component.MarkupNodes).DistinctBy(node => node.TagName))
            sb.AppendLine($"import {{ mount{ToPascalCase(child.TagName)} }} from './{child.TagName}.g.js';");

        if (FindComponents(component.MarkupNodes).Any())
            sb.AppendLine();

        var functionName = $"mount{ToPascalCase(component.Name)}";
        sb.AppendLine($"export function {functionName}(target, props = {{}}) {{");
        sb.AppendLine("  const __root = target;");
        sb.AppendLine("  const __props = props;");
        GenerateStateInitialization(sb, component);
        sb.AppendLine();
        GenerateStructuralSetup(sb, component);
        GenerateUpdateFunction(sb, component, reactionGraph);
        sb.AppendLine();
        GenerateEventListeners(sb, component);
        GenerateComponentMounts(sb, component);
        sb.AppendLine();
        sb.AppendLine("  update();");
        if (component.Parameters.Count > 0 || component.EventCallbacks.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("  return {");
            sb.AppendLine("    updateProps(nextProps) {");
            foreach (var parameter in component.Parameters)
                sb.AppendLine($"      if (nextProps.{ToCamelCase(parameter.Name)} !== undefined) {ToCamelCase(parameter.Name)} = nextProps.{ToCamelCase(parameter.Name)};");
            foreach (var callback in component.EventCallbacks)
                sb.AppendLine($"      if (nextProps.{ToCamelCase(callback.Name)} !== undefined) {ToCamelCase(callback.Name)} = nextProps.{ToCamelCase(callback.Name)};");
            sb.AppendLine("      update();");
            sb.AppendLine("    }");
            sb.AppendLine("  };");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateStateInitialization(StringBuilder sb, ComponentModel component)
    {
        foreach (var state in component.StateVariables)
        {
            if (component.Parameters.Any(parameter => parameter.Name == state.Name) ||
                component.EventCallbacks.Any(callback => callback.Name == state.Name))
                continue;
            if (state.IsComputed)
                continue;

            var value = state.InitialValue;
            if (string.IsNullOrWhiteSpace(value))
                value = DefaultValue(state.Type);

            sb.AppendLine($"  let {ToCamelCase(state.Name)} = {Translate(value, component)};");
        }

        foreach (var parameter in component.Parameters)
            sb.AppendLine($"  let {ToCamelCase(parameter.Name)} = __props.{ToCamelCase(parameter.Name)};");
        foreach (var callback in component.EventCallbacks)
            sb.AppendLine($"  let {ToCamelCase(callback.Name)} = __props.{ToCamelCase(callback.Name)};");
    }

    private static void GenerateUpdateFunction(
        StringBuilder sb,
        ComponentModel component,
        ReactionGraph graph)
    {
        sb.AppendLine("  function update() {");

        foreach (var computed in component.StateVariables.Where(state => state.IsComputed &&
                     !string.IsNullOrWhiteSpace(state.ComputedExpression)))
        {
            sb.AppendLine($"    const {ToCamelCase(computed.Name)} = {TranslateComputed(computed.ComputedExpression!, component)};");
        }

        var bindings = FindTextBindings(component.MarkupNodes).ToList();
        foreach (var binding in bindings)
        {
            var selector = binding.TagName;
            var expression = ToTemplateExpression(binding.Content, component);
            sb.AppendLine($"    __root.querySelectorAll('{EscapeJavaScript(selector)}').forEach((el) => el.textContent = {expression});");
        }

        foreach (var structural in FindStructuralNodes(component.MarkupNodes))
        {
            if (structural is RazorIfNode conditional)
                sb.AppendLine($"    __updateIf{conditional.LineNumber}();");
            else if (structural is RazorForEachNode loop)
                sb.AppendLine($"    __updateForEach{loop.LineNumber}();");
        }

        sb.AppendLine("  }");
    }

    private static void GenerateEventListeners(StringBuilder sb, ComponentModel component)
    {
        foreach (var binding in FindEventBindings(component.MarkupNodes))
        {
            var eventName = binding.Attribute.Name.TrimStart('@').ToLowerInvariant();
            var domEvent = eventName.StartsWith("on", StringComparison.Ordinal) ? eventName[2..] : eventName;
            var selector = EscapeJavaScript(binding.TagName);
            sb.AppendLine($"  __root.querySelectorAll('{selector}').forEach((el) => el.addEventListener('{domEvent}', (event) => {{");

            var handler = component.EventHandlers.FirstOrDefault(candidate =>
                string.Equals(candidate.Name, binding.Attribute.Value?.TrimStart('@'), StringComparison.Ordinal));
            if (handler is not null)
                GenerateHandlerBody(sb, handler, component);
            else if (!string.IsNullOrWhiteSpace(binding.Attribute.Value))
                GenerateInlineHandler(sb, binding.Attribute.Value!, component);

            sb.AppendLine("    update();");
            sb.AppendLine("  }));");
        }
    }

    private static void GenerateHandlerBody(StringBuilder sb, EventHandler handler, ComponentModel component)
    {
        var body = handler.Body.Trim();
        if (body.StartsWith("=>", StringComparison.Ordinal))
            body = body[2..].Trim();

        if (body.StartsWith("{", StringComparison.Ordinal))
        {
            var root = CSharpSyntaxTree.ParseText($"class __Handler {{ void Run() {body} }}").GetRoot();
            foreach (var statement in root.DescendantNodes().OfType<ExpressionStatementSyntax>())
                sb.AppendLine($"    {Translate(statement.Expression.ToString(), component)};");
            return;
        }

        if (body.Length > 0)
            sb.AppendLine($"    {Translate(body, component).TrimEnd(';')};");
    }

    private static void GenerateInlineHandler(StringBuilder sb, string expression, ComponentModel component)
    {
        var translated = Translate(expression.TrimStart('@'), component);
        sb.AppendLine($"    const __callback = {translated};");
        sb.AppendLine("    if (typeof __callback === 'function') __callback(event);");
    }

    private static void GenerateStructuralSetup(StringBuilder sb, ComponentModel component)
    {
        foreach (var node in FindStructuralNodes(component.MarkupNodes))
        {
            switch (node)
            {
                case RazorIfNode conditional:
                    sb.AppendLine($"  const __ifAnchor{conditional.LineNumber} = document.createComment('if:{conditional.LineNumber}');");
                    sb.AppendLine($"  const __ifTemplate{conditional.LineNumber} = document.createElement('template');");
                    sb.AppendLine($"  __ifTemplate{conditional.LineNumber}.innerHTML = `{EscapeTemplate(RenderMarkup(conditional.Children))}`;");
                    sb.AppendLine($"  let __ifNodes{conditional.LineNumber} = [];");
                    sb.AppendLine($"  function __updateIf{conditional.LineNumber}() {{");
                    sb.AppendLine($"    const __enabled = {Translate(conditional.Condition, component)};");
                    sb.AppendLine($"    if (__enabled && __ifNodes{conditional.LineNumber}.length === 0) {{");
                    sb.AppendLine($"      const __fragment = __ifTemplate{conditional.LineNumber}.content.cloneNode(true);");
                    sb.AppendLine($"      __ifNodes{conditional.LineNumber} = Array.from(__fragment.childNodes);");
                    sb.AppendLine($"      __ifAnchor{conditional.LineNumber}.parentNode.insertBefore(__fragment, __ifAnchor{conditional.LineNumber});");
                    sb.AppendLine("    }");
                    sb.AppendLine($"    if (!__enabled && __ifNodes{conditional.LineNumber}.length > 0) {{");
                    sb.AppendLine($"      __ifNodes{conditional.LineNumber}.forEach((node) => node.remove());");
                    sb.AppendLine($"      __ifNodes{conditional.LineNumber} = [];");
                    sb.AppendLine("    }");
                    sb.AppendLine("  }");
                    sb.AppendLine($"  __root.appendChild(__ifAnchor{conditional.LineNumber});");
                    break;
                case RazorForEachNode loop:
                    sb.AppendLine($"  const __forEachAnchor{loop.LineNumber} = document.createComment('foreach:{loop.LineNumber}');");
                    sb.AppendLine($"  const __forEachTemplate{loop.LineNumber} = document.createElement('template');");
                    sb.AppendLine($"  let __forEachNodes{loop.LineNumber} = [];");
                    sb.AppendLine($"  function __updateForEach{loop.LineNumber}() {{");
                    sb.AppendLine($"    const __items = {Translate(loop.CollectionExpression, component)} || [];");
                    sb.AppendLine($"    __forEachNodes{loop.LineNumber}.forEach((node) => node.remove());");
                    sb.AppendLine($"    __forEachNodes{loop.LineNumber} = [];");
                    sb.AppendLine($"    for (const {loop.IterationVariable} of __items) {{");
                    sb.AppendLine($"      __forEachTemplate{loop.LineNumber}.innerHTML = `{EscapeTemplate(RenderMarkup(loop.Children, loop.IterationVariable))}`;");
                    sb.AppendLine($"      const __fragment = __forEachTemplate{loop.LineNumber}.content.cloneNode(true);");
                    sb.AppendLine($"      __forEachNodes{loop.LineNumber}.push(...Array.from(__fragment.childNodes));");
                    sb.AppendLine($"      __forEachAnchor{loop.LineNumber}.parentNode.insertBefore(__fragment, __forEachAnchor{loop.LineNumber});");
                    sb.AppendLine("    }");
                    sb.AppendLine("  }");
                    sb.AppendLine($"  __root.appendChild(__forEachAnchor{loop.LineNumber});");
                    break;
            }
        }
    }

    private static void GenerateComponentMounts(StringBuilder sb, ComponentModel component)
    {
        foreach (var node in FindComponents(component.MarkupNodes))
        {
            var props = node.Attributes
                .Where(attribute => !attribute.IsEvent && attribute.Value is not null)
                .Select(attribute => $"{ToCamelCase(attribute.Name)}: {Translate(attribute.Value!, component)}")
                .ToList();
            foreach (var attribute in node.Attributes.Where(attribute => attribute.IsEvent && attribute.Value is not null))
                props.Add($"{ToCamelCase(attribute.Name)}: {Translate(attribute.Value!, component)}");

            sb.AppendLine($"  const __{ToCamelCase(node.TagName)} = mount{ToPascalCase(node.TagName)}(__root, {{ {string.Join(", ", props)} }});");
        }
    }

    private static IEnumerable<(string TagName, string Content)> FindTextBindings(IEnumerable<RazorMarkupNode> nodes)
    {
        foreach (var element in nodes.OfType<RazorElementNode>())
        {
            var directText = string.Concat(element.Children.OfType<RazorTextNode>().Select(text => text.Content));
            if (directText.Contains('@', StringComparison.Ordinal))
                yield return (element.TagName, directText);

            foreach (var nested in FindTextBindings(element.Children))
                yield return nested;
        }

        foreach (var conditional in nodes.OfType<RazorIfNode>())
        {
            foreach (var nested in FindTextBindings(conditional.Children))
                yield return nested;
            foreach (var nested in FindTextBindings(conditional.ElseChildren))
                yield return nested;
        }

    }

    private static IEnumerable<(string TagName, RazorAttribute Attribute)> FindEventBindings(IEnumerable<RazorMarkupNode> nodes)
    {
        foreach (var element in nodes.OfType<RazorElementNode>())
        {
            foreach (var attribute in element.Attributes.Where(attribute => attribute.IsEvent))
                yield return (element.TagName, attribute);
            foreach (var nested in FindEventBindings(element.Children))
                yield return nested;
        }
    }

    private static IEnumerable<RazorComponentNode> FindComponents(IEnumerable<RazorMarkupNode> nodes)
    {
        foreach (var component in nodes.OfType<RazorComponentNode>())
            yield return component;
        foreach (var element in nodes.OfType<RazorElementNode>())
            foreach (var nested in FindComponents(element.Children))
                yield return nested;
    }

    private static IEnumerable<RazorMarkupNode> FindStructuralNodes(IEnumerable<RazorMarkupNode> nodes)
    {
        foreach (var node in nodes)
        {
            if (node is RazorIfNode or RazorForEachNode)
                yield return node;
            foreach (var nested in FindStructuralNodes(node.Children))
                yield return nested;
            if (node is RazorIfNode conditional)
                foreach (var nested in FindStructuralNodes(conditional.ElseChildren))
                    yield return nested;
        }
    }

    private static string ToTemplateExpression(string content, ComponentModel component)
    {
        var parts = Regex.Split(content, @"(@[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*)");
        var template = new StringBuilder("`");
        foreach (var part in parts)
        {
            if (part.StartsWith('@'))
                template.Append("${").Append(Translate(part[1..], component)).Append('}');
            else
                template.Append(part.Replace("`", "\\`", StringComparison.Ordinal));
        }
        return template.Append('`').ToString();
    }

    private static string RenderMarkup(IEnumerable<RazorMarkupNode> nodes, string? loopVariable = null)
    {
        var result = new StringBuilder();
        foreach (var node in nodes)
        {
            switch (node)
            {
                case RazorTextNode text:
                    result.Append(ReplaceLoopExpression(text.Content, loopVariable));
                    break;
                case RazorElementNode element:
                    result.Append('<').Append(element.TagName);
                    foreach (var attribute in element.Attributes)
                    {
                        result.Append(' ').Append(attribute.Name);
                        if (attribute.Value is not null)
                            result.Append("=\"").Append(ReplaceLoopExpression(attribute.Value, loopVariable)).Append('"');
                    }
                    if (element.IsSelfClosing)
                    {
                        result.Append(" />");
                        break;
                    }
                    result.Append('>')
                        .Append(RenderMarkup(element.Children, loopVariable))
                        .Append("</").Append(element.TagName).Append('>');
                    break;
            }
        }
        return result.ToString();
    }

    private static string ReplaceLoopExpression(string value, string? loopVariable)
    {
        if (loopVariable is null)
            return value;

        var parts = Regex.Split(value, $@"(@{Regex.Escape(loopVariable)}\b)");
        var result = new StringBuilder();
        foreach (var part in parts)
            result.Append(part.StartsWith('@') ? "${" + loopVariable + "}" : part);
        return result.ToString();
    }

    private static string EscapeTemplate(string value) =>
        value.Replace("`", "\\`", StringComparison.Ordinal);

    private static string TranslateComputed(string expression, ComponentModel component) =>
        Translate(expression.Trim().TrimStart('=').Trim(), component);

    private static string Translate(string expression, ComponentModel? component = null)
    {
        try
        {
            var normalized = expression;
            if (component is not null)
            {
                foreach (var name in component.StateVariables.Select(state => state.Name)
                    .Concat(component.Parameters.Select(parameter => parameter.Name))
                    .Concat(component.EventCallbacks.Select(callback => callback.Name)))
                {
                    normalized = Regex.Replace(
                        normalized,
                        $@"\b{Regex.Escape(name)}\b",
                        ToCamelCase(name));
                }
            }

            var collection = Regex.Match(normalized,
                @"^new(?:\s+[A-Za-z_][\w<>,.]*)?\s*\(\s*\)\s*\{(?<items>.*)\}$",
                RegexOptions.Singleline);
            if (collection.Success)
                return $"[{collection.Groups["items"].Value}]";

            return CSharpExpressionToJavaScriptVisitor.Translate(normalized);
        }
        catch (ExpressionTranslationException)
        {
            return expression;
        }
    }

    private static string DefaultValue(string type) =>
        type.Trim().ToLowerInvariant() switch
        {
            "int" or "long" or "short" or "byte" or "double" or "float" or "decimal" => "0",
            "bool" => "false",
            "string" => "\"\"",
            _ => "null"
        };

    private static string EscapeJavaScript(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("'", "\\'", StringComparison.Ordinal);

    private static string ToPascalCase(string input)
    {
        var words = input.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
        return words.Length == 1
            ? char.ToUpperInvariant(words[0][0]) + words[0][1..]
            : string.Concat(words.Select(word => char.ToUpperInvariant(word[0]) + word[1..].ToLowerInvariant()));
    }

    private static string ToCamelCase(string input)
    {
        var pascal = ToPascalCase(input);
        return pascal.Length == 0 ? pascal : char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }
}
