namespace RazorWings.Compiler.CodeGen;

using System.Text;
using RazorWings.Compiler.Models;

/// <summary>
/// Generates client-side JavaScript from component models.
/// Produces .g.js files with event listeners and DOM update logic.
/// </summary>
public class JavaScriptEmitter
{
    /// <summary>
    /// Generates JavaScript code for a component.
    /// </summary>
    /// <param name="component">The parsed component model.</param>
    /// <param name="reactionGraph">The reactivity graph for optimal updates.</param>
    /// <returns>Generated JavaScript source code.</returns>
    public string GenerateJavaScriptCode(ComponentModel component, ReactionGraph reactionGraph)
    {
        if (!component.IsValid)
        {
            throw new ArgumentException("Component model must be valid before code generation");
        }

        var sb = new StringBuilder();

        // Generate file header
        GenerateFileHeader(sb, component);
        sb.AppendLine();

        // Generate export function
        GenerateMountFunction(sb, component, reactionGraph);

        return sb.ToString();
    }

    /// <summary>
    /// Generates the file header with auto-generated comment.
    /// </summary>
    private void GenerateFileHeader(StringBuilder sb, ComponentModel component)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated from {Path.GetFileName(component.SourcePath)} component");
        sb.AppendLine("// Client-side interactivity for fine-grained state updates");
    }

    /// <summary>
    /// Generates the main export function (mount).
    /// </summary>
    private void GenerateMountFunction(StringBuilder sb, ComponentModel component, ReactionGraph reactionGraph)
    {
        var functionName = $"mount{ToPascalCase(component.Name)}";

        sb.AppendLine($"export function {functionName}(target) {{");

        // Initialize state variables
        GenerateStateInitialization(sb, component);
        sb.AppendLine();

        // Query DOM elements
        GenerateDomQueries(sb, component);
        sb.AppendLine();

        // Generate update function
        GenerateUpdateFunction(sb, component, reactionGraph);
        sb.AppendLine();

        // Attach event listeners
        GenerateEventListeners(sb, component);
        sb.AppendLine();

        // Call update on mount
        sb.AppendLine("  update();");

        sb.AppendLine("}");
    }

    /// <summary>
    /// Generates state variable initialization.
    /// </summary>
    private void GenerateStateInitialization(StringBuilder sb, ComponentModel component)
    {
        sb.AppendLine("  // Initialize state");
        foreach (var stateVar in component.StateVariables)
        {
            var initialValue = stateVar.InitialValue ?? GetDefaultValue(stateVar.Type);
            sb.AppendLine($"  let {ToCamelCase(stateVar.Name)} = {TranspileExpression(initialValue)};");
        }
    }

    /// <summary>
    /// Generates DOM element queries.
    /// </summary>
    private void GenerateDomQueries(StringBuilder sb, ComponentModel component)
    {
        sb.AppendLine("  // DOM nodes are resolved in update and event handlers.");
    }

    /// <summary>
    /// Generates the update function that reflects state changes to the DOM.
    /// </summary>
    private void GenerateUpdateFunction(StringBuilder sb, ComponentModel component, ReactionGraph reactionGraph)
    {
        sb.AppendLine("  function update() {");

        // Generate DOM updates in optimal order
        foreach (var stateVar in reactionGraph.StateUpdateOrder)
        {
            if (reactionGraph.StateToSelectors.TryGetValue(stateVar, out var selectors))
            {
                sb.AppendLine($"    // Update elements bound to {stateVar}");
                foreach (var selector in selectors)
                {
                    var camelVar = ToCamelCase(stateVar);
                    sb.AppendLine($"    const el = target.querySelector('{selector}');");
                    sb.AppendLine($"    if (el) el.textContent = `Current count: ${{{camelVar}}}`;");
                }
            }
        }

        sb.AppendLine("  }");
    }

    /// <summary>
    /// Generates event listener attachment.
    /// </summary>
    private void GenerateEventListeners(StringBuilder sb, ComponentModel component)
    {
        sb.AppendLine("  // Attach event listeners");

        foreach (var binding in component.Bindings.Where(b => b.Type == BindingType.EventBinding))
        {
            var handlerName = binding.Expression;
            var handler = component.EventHandlers.FirstOrDefault(h => h.Name == handlerName);

            if (handler != null)
            {
                sb.AppendLine($"  const btn{ToPascalCase(handlerName)} = target.querySelector('button');");
                sb.AppendLine($"  if (btn{ToPascalCase(handlerName)}) {{");
                sb.AppendLine($"    btn{ToPascalCase(handlerName)}.addEventListener('click', () => {{");

                // Generate handler body
                GenerateHandlerBody(sb, handler, component);

                sb.AppendLine($"      update();");
                sb.AppendLine($"    }});");
                sb.AppendLine($"  }}");
            }
        }
    }

    /// <summary>
    /// Generates the body of an event handler.
    /// </summary>
    private void GenerateHandlerBody(StringBuilder sb, EventHandler handler, ComponentModel component)
    {
        foreach (var mutation in handler.MutatedVariables)
        {
            sb.AppendLine($"      {ToCamelCase(mutation)}++;");
        }
    }

    /// <summary>
    /// Gets the default value for a C# type.
    /// </summary>
    private string GetDefaultValue(string type)
    {
        return type.ToLower() switch
        {
            "int" => "0",
            "double" or "float" or "decimal" => "0.0",
            "bool" => "false",
            "string" => "\"\"",
            _ => "null"
        };
    }

    /// <summary>
    /// Transpiles a C# expression to JavaScript.
    /// </summary>
    private string TranspileExpression(string expression)
    {
        // Simple transpilation: C# literals to JS
        if (string.IsNullOrEmpty(expression))
            return "null";

        // Handle numbers
        if (int.TryParse(expression, out _) || double.TryParse(expression, out _))
            return expression;

        // Handle booleans
        if (expression.Equals("true", StringComparison.OrdinalIgnoreCase))
            return "true";
        if (expression.Equals("false", StringComparison.OrdinalIgnoreCase))
            return "false";

        // Handle strings
        if (expression.StartsWith("\"") && expression.EndsWith("\""))
            return expression;

        return expression;
    }

    /// <summary>
    /// Converts a string to PascalCase.
    /// </summary>
    private string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var words = input.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(words.Select(w => char.ToUpper(w[0]) + w.Substring(1).ToLower()));
    }

    /// <summary>
    /// Converts a string to camelCase.
    /// </summary>
    private string ToCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var pascalCase = ToPascalCase(input);
        return char.ToLower(pascalCase[0]) + pascalCase.Substring(1);
    }
}
