namespace RazorWings.Compiler.CodeGen;

using System.Text;
using RazorWings.Compiler.Models;

/// <summary>
/// Generates server-side rendered (SSR) C# classes from component models.
/// Produces .g.cs files that contain a Render() method for initial HTML generation.
/// </summary>
public class SsrGenerator
{
    /// <summary>
    /// Generates SSR C# code for a component.
    /// </summary>
    /// <param name="component">The parsed component model.</param>
    /// <param name="reactionGraph">The reactivity graph (optional, for metadata).</param>
    /// <returns>Generated C# source code.</returns>
    public string GenerateSsrCode(ComponentModel component, ReactionGraph? reactionGraph = null)
    {
        if (!component.IsValid)
        {
            throw new ArgumentException("Component model must be valid before code generation");
        }

        var sb = new StringBuilder();

        // Generate file header
        GenerateFileHeader(sb, component);

        // Generate namespace
        sb.AppendLine($"namespace {component.Namespace};");
        sb.AppendLine();

        // Generate class
        GenerateClass(sb, component);

        return sb.ToString();
    }

    /// <summary>
    /// Generates the file header with using statements.
    /// </summary>
    private void GenerateFileHeader(StringBuilder sb, ComponentModel component)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated from {Path.GetFileName(component.SourcePath)} component");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using RazorWings.Core;");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates the component class with render method.
    /// </summary>
    private void GenerateClass(StringBuilder sb, ComponentModel component)
    {
        var className = ToPascalCase(component.Name);

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Server-side renderer for {component.Name} component.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public partial class {className}Renderer");
        sb.AppendLine("{");

        // Generate state parameters for Render method
        GenerateRenderMethod(sb, component);

        sb.AppendLine("}");
    }

    /// <summary>
    /// Generates the Render method with state parameters.
    /// </summary>
    private void GenerateRenderMethod(StringBuilder sb, ComponentModel component)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Renders the component to an HTML string.");
        sb.AppendLine("    /// </summary>");

        // Build method signature with state parameters
        var parameterList = BuildParameterList(component.StateVariables);
        sb.AppendLine($"    public static string Render({parameterList})");
        sb.AppendLine("    {");

        // Generate HTML string
        GenerateHtmlContent(sb, component);

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// Builds the parameter list for the Render method.
    /// </summary>
    private string BuildParameterList(List<StateVariable> stateVariables)
    {
        if (stateVariables.Count == 0)
            return "";

        var parameters = stateVariables
            .Select(sv => $"{sv.Type} {ToCamelCase(sv.Name)}")
            .ToList();

        return string.Join(", ", parameters);
    }

    /// <summary>
    /// Generates the HTML content with state variable interpolation.
    /// </summary>
    private void GenerateHtmlContent(StringBuilder sb, ComponentModel component)
    {
        // Use string builder for efficient HTML generation
        sb.AppendLine("        var html = new StringBuilder();");
        sb.AppendLine();

        // Parse markup and interpolate state variables
        var markupLines = component.MarkupContent.Split(new[] { "\n" }, StringSplitOptions.None);

        foreach (var line in markupLines)
        {
            if (string.IsNullOrWhiteSpace(line))
                continue;

            // Interpolate @variable references
            var interpolatedLine = InterpolateMarkupLine(line, component.StateVariables);
            sb.AppendLine($"        html.Append($\"{EscapeString(interpolatedLine)}\");");
        }

        sb.AppendLine();
        sb.AppendLine("        return html.ToString();");
    }

    /// <summary>
    /// Interpolates @variable references in a markup line for C# code.
    /// </summary>
    private string InterpolateMarkupLine(string line, List<StateVariable> stateVariables)
    {
        var result = line;

        foreach (var stateVar in stateVariables)
        {
            // Replace @variable with {variable} for C# string interpolation
            result = System.Text.RegularExpressions.Regex.Replace(
                result,
                @"@" + stateVar.Name + @"\b",
                "{" + ToCamelCase(stateVar.Name) + "}",
                System.Text.RegularExpressions.RegexOptions.IgnoreCase
            );
        }

        return result;
    }

    /// <summary>
    /// Escapes special characters for C# string literals.
    /// </summary>
    private string EscapeString(string input)
    {
        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    /// <summary>
    /// Converts a string to PascalCase.
    /// </summary>
    private string ToPascalCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var words = input.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
        return string.Concat(words.Select(w => char.ToUpper(w[0]) + w.Substring(1).ToLower()));
    }

    /// <summary>
    /// Converts a string to camelCase.
    /// </summary>
    private string ToCamelCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var pascalCase = ToPascalCase(input);
        return char.ToLower(pascalCase[0]) + pascalCase.Substring(1);
    }
}
