namespace RazorWings.Compiler.CodeGen;

using System.Text;
using System.Text.RegularExpressions;
using RazorWings.Compiler.Models;

/// <summary>Generates SSR C# for the supported structured Razor subset.</summary>
public sealed class SsrGenerator
{
    public string GenerateSsrCode(ComponentModel component, ReactionGraph? reactionGraph = null)
    {
        if (!component.IsValid)
            throw new ArgumentException("Component model must be valid before code generation");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// Generated from {Path.GetFileName(component.SourcePath)} component");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using RazorWings.Core;");
        sb.AppendLine();
        sb.AppendLine($"namespace {component.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {ToPascalCase(component.Name)}Renderer");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string Render({BuildParameterList(component)})");
        sb.AppendLine("    {");
        sb.AppendLine("        var html = new StringBuilder();");
        foreach (var computed in component.StateVariables.Where(state =>
                     state.IsComputed && !string.IsNullOrWhiteSpace(state.ComputedExpression)))
        {
            sb.Append("        var ").Append(ToCamelCase(computed.Name)).Append(" = ")
                .Append(RewriteCSharpExpression(computed.ComputedExpression!, component))
                .AppendLine(";");
        }
        GenerateNodes(sb, component.MarkupNodes, component, 8);
        sb.AppendLine("        return html.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string BuildParameterList(ComponentModel component)
    {
        var parameters = component.StateVariables
            .Where(state => !state.IsComputed &&
                !component.EventCallbacks.Any(callback =>
                    string.Equals(callback.Name, state.Name, StringComparison.Ordinal)))
            .Select(state => $"{state.Type} {ToCamelCase(state.Name)}")
            .ToList();

        return string.Join(", ", parameters);
    }

    private static void GenerateNodes(
        StringBuilder sb,
        IEnumerable<RazorMarkupNode> nodes,
        ComponentModel component,
        int indent)
    {
        foreach (var node in nodes)
        {
            switch (node)
            {
                case RazorTextNode text:
                    AppendMarkup(sb, text.Content, component, indent);
                    break;
                case RazorElementNode element:
                    AppendElement(sb, element, component, indent);
                    break;
                case RazorIfNode conditional:
                    sb.Append(' ', indent).Append("if (")
                        .Append(RewriteExpression(conditional.Condition, component))
                        .AppendLine(")");
                    sb.Append(' ', indent).AppendLine("{");
                    GenerateNodes(sb, conditional.Children, component, indent + 4);
                    sb.Append(' ', indent).AppendLine("}");
                    if (conditional.ElseChildren.Count > 0)
                    {
                        sb.Append(' ', indent).AppendLine("else");
                        sb.Append(' ', indent).AppendLine("{");
                        GenerateNodes(sb, conditional.ElseChildren, component, indent + 4);
                        sb.Append(' ', indent).AppendLine("}");
                    }
                    break;
                case RazorForEachNode loop:
                    sb.Append(' ', indent).Append("foreach (var ")
                        .Append(loop.IterationVariable).Append(" in ")
                        .Append(RewriteExpression(loop.CollectionExpression, component))
                        .AppendLine(")");
                    sb.Append(' ', indent).AppendLine("{");
                    GenerateNodes(sb, loop.Children, component, indent + 4);
                    sb.Append(' ', indent).AppendLine("}");
                    break;
            }
        }
    }

    private static void AppendElement(
        StringBuilder sb,
        RazorElementNode element,
        ComponentModel component,
        int indent)
    {
        var opening = new StringBuilder("<").Append(element.TagName);
        foreach (var attribute in element.Attributes)
        {
            opening.Append(' ').Append(attribute.Name);
            if (attribute.Value is not null)
                opening.Append("=\"").Append(attribute.Value).Append("\"");
        }

        if (element.IsSelfClosing)
        {
            AppendMarkup(sb, opening.Append(" />").ToString(), component, indent);
            return;
        }

        AppendMarkup(sb, opening.Append(">").ToString(), component, indent);
        GenerateNodes(sb, element.Children, component, indent);
        AppendMarkup(sb, $"</{element.TagName}>", component, indent);
    }

    private static void AppendMarkup(
        StringBuilder sb,
        string markup,
        ComponentModel component,
        int indent)
    {
        if (string.IsNullOrEmpty(markup))
            return;

        var expression = RewriteExpression(markup, component);
        sb.Append(' ', indent).Append("html.Append($\"")
            .Append(EscapeString(expression))
            .AppendLine("\");");
    }

    private static string RewriteExpression(string expression, ComponentModel component)
    {
        var result = expression;
        foreach (var state in component.StateVariables)
        {
            var name = Regex.Escape(state.Name);
            result = Regex.Replace(
                result,
                $@"@{name}\b",
                "{" + ToCamelCase(state.Name) + "}",
                RegexOptions.CultureInvariant);
        }

        return result;
    }

    private static string RewriteCSharpExpression(string expression, ComponentModel component)
    {
        var result = expression;
        foreach (var state in component.StateVariables)
        {
            result = Regex.Replace(
                result,
                $@"\b{Regex.Escape(state.Name)}\b",
                ToCamelCase(state.Name),
                RegexOptions.CultureInvariant);
        }

        return result;
    }

    private static string EscapeString(string input) =>
        input.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);

    private static string ToPascalCase(string input)
    {
        var words = input.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
        return words.Length == 1
            ? char.ToUpperInvariant(words[0][0]) + words[0][1..]
            : string.Concat(words.Select(word => char.ToUpperInvariant(word[0]) + word[1..].ToLowerInvariant()));
    }

    private static string ToCamelCase(string input)
    {
        var pascal = ToPascalCase(input);
        return pascal.Length == 0 ? pascal : char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }
}
